const ACTIONS={
    LOGIN:'LOGIN',
    GET_TOKEN:'GET_TOKEN',
    GET_USER:'GET_USER',
    GET_EXAMS:'GEt_EXAMS',
    GET_CATEGORY:'GET_CATEGORY',
    GET_QUESTIONS:'GET_QUESTIONS'
}

export default ACTIONS